version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  release:
    parameters:
      target:
        type: enum
        enum: ['win10-x64', 'linux-x64', 'osx.10.14-x64']
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v3-{{ checksum "FiboLibraryTest/FiboLibraryTest.csproj" }}
      - run:
          command: dotnet publish -c Release -r << parameters.target >>
          shell: cmd.exe
      - store_artifacts:
          path: fibo/bin/Release/netcoreapp3.1/<< parameters.target >>/publish

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v3-{{ checksum "FiboLibraryTest/FiboLibraryTest.csproj" }}
      - run:
          command: dotnet build
          shell: cmd.exe
      - save_cache:
          paths:
              - C:짜Users짜circleci짜.nuget짜packages
          key:
            - dotnet-packages-v3-{{ checksum "FiboLibraryTest/FiboLibraryTest.csproj" }}
  test:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v3-{{ checksum "FiboLibraryTest/FiboLibraryTest.csproj" }}
      - run:
          command: dotnet test
          shell: cmd.exe
  release-win10-x64:
    executor: win/default
    steps:
      - release:
          target: win10-x64
  release-linux-x64:
    executor: win/default
    steps:
      - release:
          target: linux-x64
  release-osx1014-x64:
    executor: win/default
    steps:
      - release:
          target: osx.10.14-x64
  
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - release-win10-x64:
          requires:
            - test
      - release-linux-x64:
          requires:
            - test
      - release-osx1014-x64:
          requires:
            - test