version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          command: dotnet build
          shell: cmd.exe
      - persist_to_workspace:
          root: .
          paths:
            - src/ClassLibrary/bin
  test:
    executor: win/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: dotnet test
          shell: cmd.exe
  release-win:
    executor: win/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: dotnet publish -c Release -r win10-x64
          shell: cmd.exe
      - store_artifacts:
          path: src/fibo/bin/Release/netcoreapp3.1/publish
  
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - release:
          requires:
            - test