version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          command: dotnet build
          shell: cmd.exe
      - persist_to_workspace:
          paths:
            - src/ClassLibrary/bin
  test:
    executor: win/default
    steps:
      - checkout
      - attach_workspace
      - run:
          command: dotnet test
          shell: cmd.exe
  
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires: 
            - build